### ISSUE TITLE
[Bug] The 'queries' parameter has been deprecated in VectorServiceBlockingStub

### ISSUE THREAD

**Issue by AriJordan** [pinecone-io/pinecone-java-client#21]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This line:
QueryResponse queryResponse = conn.getBlockingStub().query(batchQueryRequest);

causes an exception, see below.

### Expected Behavior

The Java client shouldn't use deprecated field.

### Steps To Reproduce

I guess your example should also fail.
Maybe need to create a new Pinecone project first, which is what I did.

### Relevant log output

```shell
exception [Request processing failed: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: The 'queries' parameter has been deprecated.] with root cause

io.grpc.StatusRuntimeException: INVALID_ARGUMENT: The 'queries' parameter has been deprecated.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.53.0.jar:1.53.0]     
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.53.0.jar:1.53.0]
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.53.0.jar:1.53.0]
        at io.pinecone.proto.VectorServiceGrpc$VectorServiceBlockingStub.query(VectorServiceGrpc.java:541) ~[pinecone-client-0.2.3.jar:0.2.3]
```

### Environment

```markdown
- **OS**:
Windows 11
- **Language**
Java
- **Pinecone client version**:
0.2.3
```

**Comment by rohanshah18** [comment]
Hi @AriJordan, 
Thanks for opening this issue. Let me do some research and get back to you. Also I'm able to successfully run a batch query  call as described in the example. I'm curious to know what version of java are you using and how does the setup look like for your batch query call.
Rohan

**Comment by AriJordan** [comment]
I created a new Pinecone project on a different server and now it's fine. So it only seems to happen for some Pinecone projects/servers. Seems to have nothing to do with the Java version.

**Comment by rohanshah18** [comment]
I'm glad you were able to run the project. I'll close this but feel free to open a new issue if you face similar problems in future.

**Comment by rohanshah18** [comment]
@AriJordan Just to confirm, `addQueries()` and `addAllQueries()` are deprecated, please use `addVector()` or `addAllVector()` instead.

**Comment by rohanshah18** [comment]
@AriJordan For your reference, please find below the examples:
```java
float[] rawVector = {1.0F, 2.0F, 3.0F};
QueryVector queryVector = QueryVector.newBuilder()
        .addAllValues(Floats.asList(rawVector))
        .setFilter(Struct.newBuilder()
                .putFields("some_field", Value.newBuilder()
                        .setStructValue(Struct.newBuilder()
                                .putFields("$lt", Value.newBuilder()
                                        .setNumberValue(3)
                                        .build()))
                        .build())
                .build())
        .setNamespace(namespace)
        .build();

QueryRequest batchQueryRequest = QueryRequest.newBuilder()
        // DEPRECATED: Please use addVector() or addAllVector() instead
        .addQueries(queryVector)
        .setNamespace(namespace)
        .setTopK(2)
        .setIncludeMetadata(true)
        .build();

// Following should result in invalidArgument error
QueryResponse queryResponse = conn.getBlockingStub().query(batchQueryRequest); 

// AddAllVector() example for 3 dimensional vector
Iterable<Float> iterable = Arrays.asList(1.0F, 2.0F, 3.0F);
QueryRequest queryRequest = QueryRequest.newBuilder()
        .addAllVector(iterable)
        .setNamespace(namespace)
        .setTopK(2)
        .setIncludeMetadata(true)
        .build();

queryResponse = conn.getBlockingStub().query(queryRequest);
assertThat(queryResponse, notNullValue());
assertThat(queryResponse.getMatchesList(), notNullValue());
assertThat(queryResponse.getMatchesCount(), equalTo(2));
```

```java
// AddVector() example for a 3 dimensional vector:
QueryRequest queryRequest = QueryRequest.newBuilder()
        .addVector(101F) 
        .addVector(102F)
        .addVector(103F)
        .setNamespace(namespace)
        .setTopK(2)
        .setIncludeMetadata(true)
        .build();

queryResponse = conn.getBlockingStub().query(queryRequest);
assertThat(queryResponse, notNullValue());
```

**Comment by AriJordan** [comment]
Thanks for the help
