### ISSUE TITLE
[Bug] JAVA api returns UNAUTHENTICATED: Unauthorized when used against a trial account

### ISSUE THREAD

**Issue by monzonj** [pinecone-io/pinecone-java-client#73]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The example `MinimalUpsertAndQueryExample` returns `UNAUTHENTICATED: Unauthorized` when run against a pinecone index.

### Expected Behavior

The example upsert should work with a trial account. Issue might exist with all account types, but i've only tested it with a trial one.

### Steps To Reproduce

1. Create a trial account in https://app.pinecone.io
2. Run `MinimalUpsertAndQueryExample` in this repository, replacing api key, index name, environment adn project name with the values from your trial account
3. Run `MinimalUpsertAndQueryExample` 

the result is 
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNAUTHENTICATED: Unauthorized
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at io.pinecone.proto.VectorServiceGrpc$VectorServiceBlockingStub.upsert(VectorServiceGrpc.java:477)
	at MinimalUpsertAndQueryExample.main(MinimalUpsertAndQueryExample.java:61)
```

### Environment

```markdown
- **OS**: MacOS
- **Language version**: Java 21
- **Pinecone client version**: 0.8.0
```

**Comment by monzonj** [comment]
Sorry, actually it works. Only that the 'project name' parameter that dhows in Pinecode UI is not the right value. I debugged it and got what the real project name would be (some random string) and it works now.

Please disregard.
